# ==========================================
# Пользовательский конфиг icheck
# ==========================================

# Приоритетные хосты для проверки доступности (через ping)
# Писать через пробел.
#CUSTOM_PING_TARGETS="google.com 9.9.9.9"

# Приоритетные сайты для проверки обхода блокировок (через curl HTTPS)
# Писать через пробел.
#CUSTOM_HTTP_TARGETS="rutracker.org linkedin.com"
